const foodData = [
    {
      id: 1,
      name: "Onion Samosa",
      price: 15,
      image: "/pictures/sam1.png",
      description: "Crispy, golden-fried Samosa",
    },
    {
      id: 2,
      name: "Aloo Samosa",
      price: 20,
      image: "/pictures/sam2.png",
      description: "Crispy, golden-fried Samosa",
    },
    {
      id: 3,
      name: "Chicken Samosa",
      price: 25,
      image: "/pictures/sam3.png",
      description: "Crispy, golden-fried  Chciken Samosa",
    },
    {
      id: 4,
      name: "Chicken Biryani",
      price: 125,
      image: "/pictures/bir1.png",
      description: "Delicious spiced rice with meat",
    },
    {
      id: 5,
      name: "Egg Biryani",
      price: 99,
      image: "/pictures/bir2.png",
      description: "Fragrant rice cooked with aromatic spices and boiled eggs.",
    },
    {
      id: 6,
      name: "Paneer Biryani",
      price: 140,
      image: "/pictures/bir3.png",
      description: "Flavorful biryani with marinated paneer and aromatic spices.",
    },
    {
      id: 6,
      name: "Chicken Burger",
      price: 99,
      image: "/pictures/bur1.png",
      description: "Juicy chicken patty with fresh lettuce, cheese, and creamy sauce.",
    },
    {
      id: 7,
      name: "Veg Burger",
      price: 79,
      image: "/pictures/bur2.png",
      description: "Crispy veggie patty with fresh lettuce, cheese, and creamy sauce.",
    },
    {
      id: 8,
      name: "Cheese Burger",
      price: 99,
      image: "/pictures/bur3.png",
      description: "Juicy patty topped with melted cheese, lettuce, and creamy sauce.",
    },
    {
      id: 9,
      name: "Chapathi",
      price: 50,
      image: "/pictures/chapathi.png",
      description: "Soft, warm flatbread made with whole wheat, perfect for pairing with curries",
    },
    {
      id: 10,
      name: "Chicken Puff",
      price: 40,
      image: "/pictures/chickenpuff.png",
      description: "Flaky pastry filled with spiced, tender chicken.",
    },
    {
      id: 11,
      name: "Coffee",
      price: 20,
      image: "/pictures/cof2.png",
      description: "Smooth, bold coffee with a satisfying, robust flavor.",
    },
    {
      id: 13,
      name: "Sprite",
      price: 20,
      image: "/pictures/cool3.png",
      description: "Refreshing, chilled beverage to beat the heat ",
    },
    {
      id: 14,
      name: "Pepsi",
      price: 20,
      image: "/pictures/pepsi.png",
      description: "Refreshing, chilled beverage to beat the heat ",
    },
    {
      id: 15,
      name: "Mazaa",
      price: 20,
      image: "/pictures/Mazaa.png",
      description: "Refreshing, chilled beverage to beat the heat ",
    },
    {
      id: 16,
      name: "Chocolate IceCream",
      price: 40,
      image: "/pictures/Icecream1.png",
      description: "A velvety smooth, chocolatey delight that melts in your mouth.",
    },
    {
      id: 17,
      name: "ButterScotch IceCream",
      price: 40,
      image: "/pictures/pngwing.com.png",
      description: "A creamy, caramelized delight with a rich butterscotch flavor.",
    },
    {
      id: 18,
      name: "Vannila IceCream",
      price: 40,
      image: "/pictures/vannila1.png",
      description: "A creamy, caramelized delight with a rich Vannila flavor.",
    },
    {
      id: 19,
      name: "Veg Puff",
      price: 15,
      image: "/pictures/vegpuff.png",
      description: "A crispy, flaky pastry filled with a spicy vegetable mix.",
    },
    {
      id: 20,
      name: "Egg Puff",
      price: 20,
      image: "/pictures/eggpuff.png",
      description: "A crispy, flaky pastry filled with a spicy Egg mix.",
    },
    {
      id: 21,
      name: "Chai Biscuit",
      price: 20,
      image: "/pictures/Tea-Biscuit.png",
      description: "A classic and comforting pairing of hot tea and crispy biscuits.",
    },
    {
      id: 22,
      name: "idly",
      price: 35,
      image: "/pictures/idli.png",
      description: "A soft, fluffy steamed rice cake, perfect with chutney and sambar.",
    },
    {
      id: 23,
      name: "Dosa",
      price: 40,
      image: "/pictures/dosa.png",
      description: "A crispy, golden-brown fermented crepe, best enjoyed with chutney and sambar.",
    },
    {
      id: 24,
      name: "Puri",
      price: 40,
      image: "/pictures/puri.png",
      description: "A deep-fried, puffy bread, perfect with potato curry or chana masala.",
    },
    {
      id: 25,
      name: "Paratha and Curry",
      price: 60,
      image: "/pictures/paratha.png",
      description: "A flaky, golden-brown flatbread perfectly paired with flavorful chicken and aloo curries.",
    },
    {
      id: 26,
      name: "Veg-Meal",
      price: 80,
      image: "/pictures/meals.png",
      description: "A wholesome platter of rice, curry, and sides for a satisfying meal.",
    },
    {
      id: 27,
      name: "Nonveg-Meal",
      price: 110,
      image: "/pictures/nonveg.png",
      description: "A flavorful platter featuring rice, meats, curries, and sides for a satisfying non-veg meal",
    },
    {
      id: 28,
      name: "French fries",
      price: 70,
      image: "/pictures/fries.png",
      description: "Crispy, golden fries, perfect for a savory snack or side dish",
    },
    {
      id: 29,
      name: "Veg Momos",
      price: 60,
      image: "/pictures/vmomo.png",
      description: "Delicious steamed or fried dumplings filled with a savory mix of vegetables",
    },
    {
      id: 30,
      name: "Chicken Momos",
      price: 80,
      image: "/pictures/cmomo.png",
      description: "Steamed or fried dumplings filled with flavorful minced meat",
    },
  ];
  
  export default foodData;
  